
export suitedir=/g/data/xv83/users/bxn599/ACS/model_evaluation_suite/

export run_syclops=False
export run_icclim=True
export run_icclim_1hr=True
export run_xclim=True
export run_quantiles=False
export run_MSE=False
export run_means=True

export compute_project=e53
export storage_project_list="gdata/access+gdata/xv83+scratch/xv83+gdata/py18+gdata/e53+scratch/e53+gdata/hq89+gdata/xp65"
export python_module_path="/g/data/xp65/public/modules"
export python_env="analysis3-25.10"
export user=bxn599


# run details likely to need changing between simulations
export gcm=ACCESS-ESM1-5
export scenario=historical
export realisation=r6i1p1f1
export start_year=1995
export end_year=2004


# run details likely to be more constant
#export file_frequency=monthly
#export rcm1=CCAM
#export rcm2=CCAM-v2203-SN
#export domain=AUS-10i
#export data_project=hq89
#export institution=CSIRO

export file_frequency=monthly
export rcm1=BARPA
export rcm2=BARPA-C
export domain=AUST-04
export data_project=py18
export institution=BOM

export outdir=${suitedir}/output/${gcm}/${scenario}/${realisation}/${rcm2}/
export logdir=${suitedir}/logs/${gcm}_${scenario}_${realisation}_${rcm2}/
export data_path=/g/data/${data_project}/${rcm1}/output/CMIP6/DD/${domain}/${institution}/${gcm}/${scenario}/${realisation}/${rcm2}/v1-r1/
export filename={var}_${domain}_${gcm}_${scenario}_${realisation}_${institution}_${rcm2}_v1-r1_{freq}_{year1}{month1}_{year2}{month2}.nc


# SyCLoPS options
export syclops_run_parallel=True
export syclops_run_serial=False
export syclops_scratchpath=/scratch/xv83/$user/syclops/
export syclops_TE_path=/g/data/tp28/dev/eh6215/low_tracking/tempestextremes_missingvalue/
export syclops_hourly_vars="sfcWind psl"
export syclops_3hourly_vars="ua925 ua850 ua500 ua200 va925 va850 va500 va200 ta850 hus850 zg925 zg850 zg700 zg500 zg300"
export syclops_6hourly_vars="ta100 hus100"
export syclops_mem=7GB
export syclops_ncpus=1
export syclops_queue=normalbw
export syclops_walltime="04:00:00"


# Hourly ICCLIM options
export icclim_1hr_slice_mode="year"
export icclim_1hr_walltime="12:00:00"
export icclim_1hr_mem=180GB
export icclim_1hr_jobfs=4GB
export icclim_1hr_ncpus=16
export icclim_1hr_queue=normal
export icclim_1hr_template=0.2
export icclim_1hr_input_freq=1hr
#export NUMBA_CACHE_DIR=/scratch/xv83/$user/tmp


# ICCLIM options
export icclim_indices_tasmax="tasmax:TX tasmax:SU tasmax:TXx tasmax:CSU tasmax:ID tasmax:TXn"
export icclim_indices_tasmin="tasmin:TN tasmin:TR tasmin:TNx tasmin:FD tasmin:CFD tasmin:TNn"
export icclim_indices_prcp="pr:CDD pr:PRCPTOT pr:RR1 pr:SDII pr:CWD pr:RR pr:R10mm pr:R20mm pr:RX1day pr:RX5day"
export icclim_slice_mode="year"
export icclim_walltime="04:00:00"
export icclim_mem=180GB
export icclim_jobfs=4GB
export icclim_ncpus=16
export icclim_queue=normal
export icclim_template=0.2
export NUMBA_CACHE_DIR=/scratch/xv83/$user/tmp

# RX1Day below will output RX1Hour
export icclim_1hr_indices_prcp="pr:R10mm pr:R20mm pr:RX1day"  


# xclim options
export xclim_indices_tasmax="tasmax:tx_days_above:32_degC"
export xclim_freq="year"
export xclim_walltime="04:00:00"
export xclim_mem=180GB
export xclim_jobfs=4GB
export xclim_ncpus=16
export xclim_queue=normal
export xclim_template=0.2
export NUMBA_CACHE_DIR=/scratch/xv83/$user/tmp


# Quantile options
export quantile_variables="tasmax tasmin pr sfcWind"
export quantiles_tasmax="0.9 0.95 0.99 0.999"
export quantiles_tasmin="0.1 0.05 0.01 0.001 0.9 0.95 0.99 0.999"
export quantiles_pr="0.9 0.95 0.99 0.999"
export quantiles_sfcWind="0.9 0.95 0.99 0.999"


# MSE options
export mse_freq=day
export mse_walltime="04:00:00"
export mse_mem=63GB
export mse_jobfs=4GB
export mse_ncpus=14
export mse_queue=normalbw


# seasonal_means options
export means_seas="DJF MAM JJA SON ANN"
export means_vars="pr tasmax tasmin"
export means_walltime="02:00:00"
export means_mem=12GB
export means_jobfs=4GB
export means_ncpus=2
export means_queue=normal
