export suitedir=/home/users/gov/nea/chuaxr/model_evaluation_suite/
export compute_project=17001770
export storage_project_list=""
export python_env1="source ~/.myconda"
export python_env2="conda activate research"
export outdir=/scratch/users/gov/nea/chuaxr/test-dir/20260319


