
export suitedir=/g/data/tp28/dev/eh6215/model_evaluation_suite/

export run_syclops=False
export run_icclim=True
export run_quantiles=False
export run_MSE=False
export run_radar_dist=False

export obsdata=True
export compute_project=tp28
export python_module_path="/g/data/access/ngm/modules"
export python_env="analysis3/21.10"
export user=eh6215

# run details likely to need changing between simulations
export start_year=1985
export end_year=2022


# run details likely to be more constant
export file_frequency=annual


export outdir=${suitedir}/output/obs/AGCDv2/
export logdir=${suitedir}/logs/obs_AGCDv2/
export data_path=/g/data/tp28/dev/evaluation_datasets/AGCDv2/all/
export filename=precip_total_r005_{year1}.nc


# ICCLIM options
export icclim_indices_tasmax=""
export icclim_indices_tasmin=""
export icclim_indices_prcp="precip:CDD precip:PRCPTOT precip:RR1 precip:SDII precip:CWD precip:RR precip:R10mm precip:R20mm precip:RX1day precip:RX5day"
export icclim_slice_mode="year"
export icclim_walltime="00:90:00"
export icclim_mem=180GB
export icclim_jobfs=4GB
export icclim_ncpus=16
export icclim_queue=normal
export icclim_template=0.2
export NUMBA_CACHE_DIR=/scratch/tp28/$user/tmp
export icclim_indices_prcp_1hr=""  

# Quantile options
export quantile_variables="tasmax tasmin pr sfcWind"
export quantiles_tasmax="0.9 0.95 0.99 0.999"
export quantiles_tasmin="0.1 0.05 0.01 0.001 0.9 0.95 0.99 0.999"
export quantiles_pr="0.9 0.95 0.99 0.999"
export quantiles_sfcWind="0.9 0.95 0.99 0.999"


