

export wethours_walltime="00:30:00"
export wethours_mem=10GB
export wethours_jobfs=1GB
export wethours_ncpus=4
export wethours_queue=normal
export wethours_threshold=0.2
export wethours_calcdp=False
export wethours_lonmin=100
export wethours_lonmax=101
export wethours_latmin=-1
export wethours_latmax=1
export wethours_landmask=False
