
# run details likely to need changing between simulations
export gcm=ERA5
export scenario=historical
export realisation=reanalysis
export start_year=2013
export end_year=2013

# example file paths
# /scratch/users/gov/nea/glim/V3_L1_Compressed/V3-SEA-8/CCRS/ERA5/historical/reanalysis/SINGV-RCM/vn5/day/pr/2013/pr_V3-SEA-8_ERA5_historical_reanalysis_SINGV-RCM_vn5_day_20130101-20130131.nc
# /scratch/users/gov/nea/glim/V3_L1_Compressed/V3-SEA-8/CCRS/ERA5/historical/reanalysis/SINGV-RCM/vn5/1hr/pr/201312/pr_V3-SEA-8_ERA5_historical_reanalysis_SINGV-RCM_vn5_1hr_201312010000-201312012300.nc

# run details likely to be more constant
export file_frequency=monthly # one file for each month
export rcm1=SINGV-RCM
export rcm2=vn5
export domain=V3-SEA-8
export institution=CCRS

# those with $ hard-coded for this config, {} without $ for suite to insert what is needed
export outdir=/scratch/users/gov/nea/chuaxr/test-dir/20260319/output/${gcm}/${scenario}/${realisation}/${rcm2}/
export logdir=${suitedir}/logs/${gcm}_${scenario}_${realisation}_${rcm2}/

# frequency, variable, year, month filled in by suite
export data_path=/scratch/users/gov/nea/glim/V3_L1_Compressed/${domain}/${institution}/${gcm}/${scenario}/reanalysis/${rcm1}/${rcm2}/{freq}/{var}/{year1}*/

export filename={var}_${domain}_${gcm}_${scenario}_${realisation}_${rcm1}_${rcm2}_{freq}_{year1}{month1}*-{year2}{month2}*.nc


