
export suitedir=/g/data/tp28/dev/eh6215/model_evaluation_suite/

export run_syclops=False
export run_icclim=False
export run_quantiles=False
export run_MSE=False
export run_radar_dist=True

export obsdata=True

# run details likely to need changing between simulations
export start_year=2013
export end_year=2021


# run details likely to be more constant
export data_project=tp28

export outdir=${suitedir}/output/obs/historical/r1i1p1f1/radar_rainrate_level2/
export logdir=${suitedir}/logs/obs_radar_rainrate_level2/
export data_path=/g/data/tp28/dev/eh6215/radar/rr2/lev2_RAINRATE/
export filename={station}_*20????_radar_rainrate_level2.nc

# Radar Distribution options
export radar_station_list="2 4 9 22 49 54 63 66 71 77"
export radar_bin=2
export radar_freq_in="20min"
export radar_freq_out="1h"
export radar_path="/g/data/tp28/dev/eh6215/radar/rr2/lev2_RAINRATE/"
export radar_grid="AUST04"
export radar_boundary_pad=1
export radar_var="rainrate"
export radar_scale_factor=1
export radar_walltime="01:00:00"
export radar_mem=18GB
export radar_jobfs=4GB
export radar_ncpus=4
export radar_queue=normalbw
export radar_outname="AUST-04_radar_rainrate_level2_${radar_freq_out}_${start_year}01_${end_year}12.nc"

