
# run details likely to need changing between simulations
export gcm=MPI-ESM1-2-HR
export scenario=historical
export realisation=r1i1p1f1
export start_year=1995
export end_year=2004


# run details likely to be more constant
export file_frequency=monthly
export rcm1=BARPA
export rcm2=BARPA-R
export domain=AUS-15
export data_project=py18
export institution=BOM

export outdir=${suitedir}/output/${gcm}/${scenario}/${realisation}/${rcm2}/
export logdir=${suitedir}/logs/${gcm}_${scenario}_${realisation}_${rcm2}/
export data_path=/g/data/${data_project}/${rcm1}/output/CMIP6/DD/${domain}/${institution}/${gcm}/${scenario}/${realisation}/${rcm2}/v1-r1/{freq}/{var}/latest/
export filename={var}_${domain}_${gcm}_${scenario}_${realisation}_${institution}_${rcm2}_v1-r1_{freq}_{year1}{month1}-{year2}{month2}.nc


