
# run details likely to need changing between simulations
export gcm=ACCESS-ESM1-5
export scenario=historical
export realisation=r6i1p1f1
export start_year=1995
export end_year=2004


# run details likely to be more constant
export file_frequency=monthly
export rcm1=CCAM
export rcm2=CCAM-v2203-SN
export domain=AUS-10i
export data_project=hq89
export institution=CSIRO

