
# run details likely to need changing between simulations
export gcm=ACCESS-ESM1-5
export scenario=historical
export realisation=r6i1p1f1
export start_year=1995
export end_year=2004


# run details likely to be more constant
export file_frequency=monthly
export rcm1=CCAM
export rcm2=CCAM-v2203-SN
export domain=AUS-10i
export data_project=hq89
export institution=CSIRO

# redeclare paths so that the above parameters are picked up
export outdir=${suitedir}/output/${gcm}/${scenario}/${realisation}/${rcm2}/
export logdir=${suitedir}/logs/${gcm}_${scenario}_${realisation}_${rcm2}/
export data_path=/g/data/${data_project}/${rcm1}/output/CMIP6/DD/${domain}/${institution}/${gcm}/${scenario}/${realisation}/${rcm2}/v1-r1/{freq}/{var}/v20231206/
export filename={var}_${domain}_${gcm}_${scenario}_${realisation}_${institution}_${rcm2}_v1-r1_{freq}_{year1}{month1}-{year2}{month2}.nc


