
# run details likely to need changing between simulations
export start_year=2013
export end_year=2021
export gcm=BARRA-C2
export scenario=historical
export realisation=v1

# run details likely to be more constant
export file_frequency=monthly
export rcm1=BARRA
export rcm2=BARRA-C2
export domain=AUST-04
export data_project=py18
export institution=BOM


export outdir=${suitedir}/output/BARRA-C2/
export logdir=${suitedir}/logs/BARRA-C2
export data_path=/g/data/ob53/BARRA2/output/reanalysis/AUST-04/BOM/ERA5/historical/hres/BARRA-C2/v1/{freq}/{var}/latest
export filename={var}_AUST-04_ERA5_historical_hres_BOM_BARRA-C2_v1_{freq}_{year1}{month1}-{year2}{month2}.nc
